name: Rami
rules:
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: Rami.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: roca (1) (1).png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: radio (1).png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: ramiyradio.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: fondo1.png
    text: null
