name: Marciano
rules:
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: marciano12322.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: pizza12332.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: Sin título.png
    text: null
