library:
  visible: false
source:
  visible: true
  percentage: 0.5499782986111111
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: low
attire:
  user_permissions:
    can_toggle_visibility: false
  visible: true
  active: Rami
initialDescription: true
link: ''
blocks:
  visible:
    - ProcedimientosPrimitivos
    - RepeticionSimple
    - DefinicionesDeProgramas
  disabled: []
activity:
  creation_mode: advanced
  construction_mode: blocks
  execution_type: sequential
name: Nuevo proyecto
